### ISSUE TITLE
Can not delete directories on remote sites with file manager

### ISSUE THREAD

**Issue by Aethylred** [grisu/grisu-template#2]
If a job goes wrong and does not clean up, you can not use the job manager to delete old directories.

**Comment by makkus** [comment]
Hey Aaron, could you open this issue on the grisu issues tracker, since it is an issue with the underlying library. It is easier to reference to issues from git commits if it is in the same repo.
Also, when you do that, can you give more details? I.e. which of the "virtual" filesystems are you using, groups, jobs, sites?
